### ISSUE TITLE
I got an error！

### ISSUE THREAD

**Issue by dingyucheng007** [taneishi/CRBM#1]
Hi Taneishi,

I am a beginner of theano. I am very sorry to bother you. When I run your crbm.py program, I get the following error:

Exception: ('The following error happened while compiling the node', InplaceDimShuffle{x,0}(vbias), '\n', 'Compilation failed (return status=1): g++.exe: error: Folder\\Anaconda3\\MinGW: No such file or directory\r. ', '[InplaceDimShuffle{x,0}(vbias)]')

I think this is not a bug in the program. I think it is a problem with my configuration or environment. I am looking forward to your guidance, which is very important to me. 

Thank you very much！

**Comment by taneishi** [comment]
Hi, this error seems a lack of g++ compiler on windows anaconda environment. In theano document, installation of m2w64-toolchain is recommended.

`conda install m2w64-toolchain`

**Comment by dingyucheng007** [comment]
Hello, teacher,

Thanks for the fast reply. I just installed m2w64-toolchain according to your suggestion, but the same error still occurs. I agree with your point of view, that is, the problem of the g++ compiler. Could you give me some advice or help?

Thank you very much!

![_20190104120109](https://user-images.githubusercontent.com/35335632/50673456-ca409380-1018-11e9-8fbd-257ead6871c3.png)
![_20190104120115](https://user-images.githubusercontent.com/35335632/50673459-d0cf0b00-1018-11e9-9391-158ef4a85e62.png)

**Comment by taneishi** [comment]
Thank you, how about `conda install mingw`?
https://stackoverflow.com/questions/36722975/theano-g-not-detected

**Comment by dingyucheng007** [comment]
Hello, teacher,

thanks for your help. According to your suggestion, I reinstalled mingw and g++. But the same problem still exists. I doubt if it is a problem with environmental variables? I have attached my environment variables below, I hope you can find my problem.

Thank you very much!

![_20190104143154](https://user-images.githubusercontent.com/35335632/50676075-39c07e00-102d-11e9-90c5-019457c038a7.png)
![_20190104143158](https://user-images.githubusercontent.com/35335632/50676079-3f1dc880-102d-11e9-882e-038ba8eb04ca.png)
![_20190104143338](https://user-images.githubusercontent.com/35335632/50676081-4349e600-102d-11e9-806c-e3da0495117f.png)

**Comment by taneishi** [comment]
I got the problem, the error message showed the file "Folder\\...\\MinGW" was not found. This is the latter part of the path for g++ executable split by whitespace. Would you reinstall Anaconda with a new path without any whitespaces?
https://github.com/Theano/Theano/issues/5183

**Comment by dingyucheng007** [comment]
Hello, teacher,

Thank you very much for your help. You are right. According to your suggestion, I reinstall Anaconda with a new path without any whitespaces. Everything is OK now.

Good luck！
