### ISSUE TITLE
theano version

### ISSUE THREAD

**Issue by 1170300814** [taneishi/CRBM#2]
hello! I want to know your theano version

**Comment by taneishi** [comment]
Hi, I confirmed this implementation with Theano-1.0.3.

**Comment by 1170300814** [comment]
thanks!!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "taneishi/crbm"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月7日(星期天) 晚上9:46
收件人:&nbsp;"taneishi/crbm"<crbm@noreply.github.com&gt;;
抄送:&nbsp;"仰望者"<1241390826@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [taneishi/crbm] theano version (#2)





 
Hi, I confirmed this implementation with Theano-1.0.3.

**Comment by 1170300814** [comment]
> Hi, I confirmed this implementation with Theano-1.0.3.

there some error happen in the latest theano.I suggest to add a illustration

**Comment by taneishi** [comment]
I added run log in the next notebook. Do you mean the last red warning?
https://github.com/taneishi/crbm/blob/master/crbm.ipynb

**Comment by 1170300814** [comment]
> I added run log in the next notebook. Do you mean the last red warning?
> https://github.com/taneishi/crbm/blob/master/crbm.ipynb

no, another error.A lot of people talk about the latest version theano has a vital bug.They said "not to use the latest version theano is the only way to solve the problem"

**Comment by taneishi** [comment]
Thanks, I specified theano-1.0.4 (perhaps theano-1.0.x) in requirements.
