### ISSUE TITLE
what is the "delay" mean

### ISSUE THREAD

**Issue by 1170300814** [taneishi/CRBM#3]
hello !  The parm has "delay=6". what the parm "delay" used for?

**Comment by taneishi** [comment]
Hi, "delay" parameter means when we start the prediction from the start time (t=0).
It is also a size of time dimension of an input tensor.
I linked the original paper by Taylor and Hinton in README, the delay parameter is noted as "N" in Fig. 4 in the paper.

**Comment by 1170300814** [comment]
ok!
